export const characterData = [
  {
    id: 1,
    name: 'Enialis Hornraven',
    race: 'Half-Elf',
    gender: 'Male',
    class: 'Warlock',
    background: 'Pirate',  
    occupation: 'Sailor',
    origin: {
      hasSiblings: true,
      familyLifestyle: 'Poor',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'Lawful Evil',
    physicalCharacteristics: {
      age: 57,
      heightInches: 69,
      weightPounds: 206,
      eyes: 'Green-flecked Gold',
      skin: 'Bronze',
      hair: 'Brown',
    }
  },
  {
    id: 2,
    name: 'Eztli',
    race: 'Yuan-Ti Pureblood',
    gender: 'Male',
    class: 'Bard',
    background: 'Acolyte',  
    occupation: 'Priest',
    origin: {
      hasSiblings: true,
      familyLifestyle: 'Modest',
      childhoodMemories: 'Ordinary',  
    },    
    alignment: 'Lawful Neutral',
    physicalCharacteristics: {
      age: 26,
      heightInches: 69,
      weightPounds: 214,
      eyes: 'Shimmering Gold',
      skin: 'Pale',
      hair: 'Blond',
    }
  },
  {
    id: 3,
    name: 'Tana "Ku" Quillsharpener',
    race: 'Gnome',
    gender: 'Female',
    class: 'Paladin',
    background: 'Soldier',
    occupation: 'Laborer',
    origin: {
      hasSiblings: false,
      familyLifestyle: 'Modest',
      childhoodMemories: 'Happy',  
    },
    alignment: 'Neutral Evil',
    physicalCharacteristics: {
      age: 119,
      heightInches: 38,
      weightPounds: 38,
      eyes: 'Glittering Blue',
      skin: 'Rocky Gray',
      hair: 'Gray White',
    }
  },
  {
    id: 4,
    name: 'Kilvar Glanhig',
    race: 'Dwarf',
    gender: 'Male',
    class: 'Paladin',
    background: 'Guild Merchant',
    occupation: 'Farmer',
    origin: {
      hasSiblings: false,
      familyLifestyle: 'Modest',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'Neutral Evil',
    physicalCharacteristics: {
      age: 118,
      heightInches: 47,
      weightPounds: 127,
      eyes: 'Hazel',
      skin: 'Dark Brown',
      hair: 'Red',
    }
  },
  {
    id: 5,
    name: 'Haseid Pashar',
    race: 'Half-Orc',
    gender: 'Male',
    class: 'Fighter',
    background: 'Pirate',
    occupation: 'Priest',
    origin: {
      hasSiblings: false,
      familyLifestyle: 'Squalid',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'True Neutral',
    physicalCharacteristics: {
      age: 54,
      heightInches: 67,
      weightPounds: 239,
      eyes: 'Gray',
      skin: 'Gray',
      hair: 'Dark Brown',
    }
  },
  {
    id: 6,
    name: 'Zed Nathandem',
    race: 'Half-Orc',
    gender: 'Male',
    class: 'Barbarian',
    background: 'Sailor',
    occupation: 'Entertainer',
    origin: {
      hasSiblings: true,
      familyLifestyle: 'Comfortable',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'Neutral Good',
    physicalCharacteristics: {
      age: 35,
      heightInches: 69,
      weightPounds: 195,
      eyes: 'Red',
      skin: 'Gray',
      hair: 'Dark Brown',
    }
  },
  {
    id: 7,
    name: 'Myathethin Yaeldrin',
    race: 'Elf',
    gender: 'Female',
    class: 'Cleric',
    background: 'Sailor',
    occupation: 'Hunter',
    origin: {
      hasSiblings: true,
      familyLifestyle: 'Modest',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'Neutral Evil',
    physicalCharacteristics: {
      age: 238,
      heightInches: 63,
      weightPounds: 109,
      eyes: 'Green',
      skin: 'Dark Copper',
      hair: 'Copper',
    }
  },
  {
    id: 8,
    name: 'Kiirith Shestendeliath',
    race: 'Dragonborn',
    gender: 'Female',
    class: 'Ranger',
    background: 'Guild Merchant',
    occupation: 'Laborer',
    origin: {
      hasSiblings: false,
      familyLifestyle: 'Modest',
      childhoodMemories: 'Lonely',  
    },
    alignment: 'Neutral Evil',
    physicalCharacteristics: {
      age: 38,
      heightInches: 76,
      weightPounds: 235,
      eyes: 'Gold',
      skin: 'Dark Brown',
      hair: 'None',
    }
  },
  {
    id: 9,
    name: 'Anastrianna Xiloscienta',
    race: 'Elf',
    gender: 'Female',
    class: 'Warlock',
    background: 'Acolyte',
    occupation: 'Artisan',
    origin: {
      hasSiblings: true,
      familyLifestyle: 'Poor',
      childhoodMemories: 'Ordinary',  
    },
    alignment: 'Neutral Evil',
    physicalCharacteristics: {
      age: 255,
      heightInches: 64,
      weightPounds: 140,
      eyes: 'Green',
      skin: 'Light Copper',
      hair: 'Copper',
    }
  },
  {
    id: 10,
    name: 'Gorstag Amblecrown',
    race: 'Human',
    gender: 'Male',
    class: 'Druid',
    background: 'Noble',
    occupation: 'Laborer',
    origin: {
      hasSiblings: false,
      familyLifestyle: 'Comfortable',
      childhoodMemories: 'Happy',  
    },
    alignment: 'Lawful Good',
    physicalCharacteristics: {
      age: 44,
      heightInches: 66,
      weightPounds: 140,
      eyes: 'Gray',
      skin: 'Fair',
      hair: 'Blond',
    }
  },
];